### PR TITLE
Handle update network status failed after add and del attachments 

### LINKED ISSUE #235: [BUG] Dynamic network plugin stuck due to updating pod network status failed
**Describe the bug**
Right now, Dynamic-network-controller will request multus and use the result to update pod network status in pod annotation `k8s.v1.cni.cncf.io/network-status`(details in `SetNetworkStatus`). When update NetworkStatus failed dynamic-network-controller just requeue the pod.
While CNI have already handle `addNetworks` request and add interface in the pod before `SetNetworkStatus`.
When the pod requeue and rehandle. Dynamic-network-controller will do `addNetworks` again according to  `k8s.v1.cni.cncf.io/network-status` on pod. While this request will always failed because interface has create in pod in the initial request. and stuck all dynamic network request for this pod.

**Expected behavior**
`SetNetworkStatus` failed dosen't stuck dynamic network request for this pod.

**To Reproduce**
1.
2.
3.

**Environment**:
- multus-dynamic-networks-controller version: N/A
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- OS (e.g. from /etc/os-release): N/A
- Controller configuration (`criSocketPath` / `multusSocketPath`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.

### PR DESCRIPTION
**Pull request by Longchuanzheng**
**What this PR does / why we need it**:
This pr delete all attachments added in this `processNextWorkItem` when set NetworkStatus failed in `handleResult`.  Because DEL is Idempotence we can always return to the state before dynamic handle.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #235

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

**Comment by Longchuanzheng** [comment]
This pr will cancel(delete) the added attachment in two cases:
1. When update network status failed in `handleResult`, we delete all attachment added in this reconcile.
2. When add attachments failed in reconcile, we try to delete add failed and all subsequent attachments that need to be added.

File: pkg/controller/pod.go [hunk 1]
```diff
@@ -334,13 +344,35 @@ func (pnc *PodNetworksController) handleResult(
 			updatedStatus,
 		); setNetworkStatusError != nil {
 			klog.Errorf("error updating pod %s network status: %v", namespacedPodNameString, setNetworkStatusError)
+			shouldDeleteattachmentsAdded = true
+		}
+	}
+
+	var attachmentsToCancal []nadv1.NetworkSelectionElement
```
Comment (LionelJouin) [inline pkg/controller/pod.go:351]:
```suggestion
	var attachmentsToCancel []nadv1.NetworkSelectionElement
```

File: pkg/controller/pod.go [hunk 2]
```diff
@@ -334,13 +344,35 @@ func (pnc *PodNetworksController) handleResult(
...
+	if shouldDeleteattachmentsAdded {
+		attachmentsToCancal = attachmentsToAdd
+	} else if addfailedIndex != -1 {
+		attachmentsToCancal = attachmentsToAdd[addfailedIndex:]
```
Comment (LionelJouin) [inline pkg/controller/pod.go:355]:
```suggestion
		attachmentsToCancal = attachmentsToAdd[:addfailedIndex]
```
Shouldn't we select the n first elements instead of the n last ones? The results are reported in the same order as the in the annotations, if it fails at attachment 3, the 3 first attachments should be removed, not the 3 last ones.

File: pkg/controller/pod.go [hunk 3]
```diff
@@ -334,13 +344,35 @@ func (pnc *PodNetworksController) handleResult(
...
+	}
+	if len(attachmentsToCancal) > 0 {
+		_, deleteattachmentsError := pnc.handleDynamicInterfaceRequest(
```
Comment (LionelJouin) [inline pkg/controller/pod.go:358]:
```suggestion
		_, deleteAttachmentsError := pnc.handleDynamicInterfaceRequest(
```

**Review by LionelJouin — COMMENTED** [review]
I think this feature makes sense. I don't know if it would be possible to add unit tests for it?

**Comment by Longchuanzheng** [comment]
> I think this feature makes sense. I don't know if it would be possible to add unit tests for it?

ok, I will try.

**Comment by Longchuanzheng** [comment]
Right now, it will return an err if we want to delet net1 in ut. If we change this, some previous ut will failed. So my ut expect `FailedRemovingInterface` for remove the net1. 
Or do we need do more in this pr to improve ut (I think it will change more codes in ut.)?

File: pkg/controller/pod.go (hunk 2 above)
Comment (LionelJouin) [reply pkg/controller/pod.go]: I think I misunderstood this part last time. Why do we need to delete the latest elements and not only the one at addfailedIndex? The controller haven't tried to ADD them, it stopped at addfailedIndex right?

File: pkg/controller/pod_test.go [hunk 4]
```diff
@@ -616,7 +629,57 @@ var _ = Describe("Dynamic Attachment controller", func() {
...
+						"Warning FailedRemovingInterface pod [%s]: failed removing interface %s from network: %s",
+						annotations.NamespacedName(namespace, podName),
+						"net1",
+						networkToAdd,
+					)
+
+					Eventually(<-eventRecorder.Events).Should(Equal(expectedEventPayload))
+				})
+
+				It("the pod network-status dosen't change", func() {
```
Comment (LionelJouin) [inline pkg/controller/pod_test.go:668]:
```suggestion
				It("the pod network-status doesn't change", func() {
```

File: pkg/controller/pod_test.go [hunk 5]
```diff
@@ -616,7 +629,57 @@ var _ = Describe("Dynamic Attachment controller", func() {
...
+						"Normal AddedInterface pod [%s]: added interface %s to network: %s",
+						annotations.NamespacedName(namespace, podName),
+						"net1",
+						networkToAdd,
+					)
 
+					Eventually(<-eventRecorder.Events).Should(Equal(expectedEventPayload))
+
+					expectedEventPayload = fmt.Sprintf(
+						"Warning FailedRemovingInterface pod [%s]: failed removing interface %s from network: %s",
```
Comment (LionelJouin) [inline pkg/controller/pod_test.go:659]: you can add `networkConfig(multuscni.CmdDel, "net1", macAddr),` to the fake multus client line 126 to test the simple case if you want (the simple case I mean: everything works except status update).

File: pkg/controller/pod_test.go (hunk 4 above)
Comment (LionelJouin) [inline pkg/controller/pod_test.go:668]: I am not sure if this is required as the status update has been prevented, so this might test Kubernetes.

File: pkg/controller/pod_test.go [hunk 6]
```diff
@@ -616,7 +629,57 @@ var _ = Describe("Dynamic Attachment controller", func() {
...
+						metav1.UpdateOptions{})
+					Expect(err).NotTo(HaveOccurred())
+				})
+
+				It("an `AddedInterface` and then a `FailedRemovingInterface` event are seen in the event recorded ", func() {
+
+					expectedError := errors.New("someerror")
+					k8sClient.PrependReactor("update", "pods", func(_ k8stesting.Action) (bool, runtime.Object, error) {
+						return true, nil, expectedError
+					})
```
Comment (LionelJouin) [inline pkg/controller/pod_test.go:647]: To be moved to the `JustBeforeEach`

**Comment by Longchuanzheng** [comment]
@maiqueb Hi, can you review this pr, thank you in advance. I think this https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/issues/235 will cause pod add/del attachnet stuck. 
It is not very friendly if we stuck when try to hotplugin nic for vm with kubevirt.

File: pkg/controller/pod_test.go [hunk 7]
```diff
@@ -3,12 +3,16 @@ package controller
 import (
 	"context"
 	"encoding/json"
+	"errors"
 	"fmt"
+	k8stesting "k8s.io/client-go/testing"
```
Comment (maiqueb) [inline pkg/controller/pod_test.go:8]: wrong place to put the import; put it below, with all the k8s.io imports.

File: pkg/controller/pod_test.go [hunk 8]
```diff
@@ -3,12 +3,16 @@ package controller
...
 	"os"
 	"path"
 	"testing"
 	"time"
 
+	"k8s.io/apimachinery/pkg/runtime"
```
Comment (maiqueb) [inline pkg/controller/pod_test.go:14]: wrong place to put the import; put it below, with all the k8s.io imports.

File: pkg/controller/pod_test.go [hunk 9]
```diff
@@ -616,7 +636,57 @@ var _ = Describe("Dynamic Attachment controller", func() {
...
+					Expect(err).NotTo(HaveOccurred())
+					expectedError := errors.New("someerror")
+                                        k8sClient.PrependReactor("update", "pods", func(_ k8stesting.Action) (bool, runtime.Object, error) {
+                                                return true, nil, expectedError
+                                        })
+				})
+
+				It("an `AddedInterface` and then a `RemovingInterface` event are seen in the event recorded ", func() {
+
+					expectedEventPayload := fmt.Sprintf(
```
Comment (maiqueb) [inline pkg/controller/pod_test.go:670]: nit: you could name this something with semantic meaning - `expectedAddInterfaceEvent` for instance.

File: pkg/controller/pod_test.go [hunk 10]
```diff
@@ -616,7 +636,57 @@ var _ = Describe("Dynamic Attachment controller", func() {
...
+						"Normal AddedInterface pod [%s]: added interface %s to network: %s",
+						annotations.NamespacedName(namespace, podName),
+						"net2",
+						networkToAdd1,
+					)
+
+					Eventually(<-eventRecorder.Events).Should(Equal(expectedEventPayload))
+
+					expectedEventPayload = fmt.Sprintf(
```
Comment (maiqueb) [inline pkg/controller/pod_test.go:679]: nit: no need to update the variable; I'd introduce a new variable, and name it something with semantic meaning - `expectedDeleteInterfaceEvent` for instance.

File: pkg/controller/pod.go [hunk 11]
```diff
@@ -334,13 +344,35 @@ func (pnc *PodNetworksController) handleResult(
...
 			klog.Errorf("error updating pod %s network status: %v", namespacedPodNameString, setNetworkStatusError)
+			shouldDeleteattachmentsAdded = true
+		}
+	}
+
+	var attachmentsToCancel []nadv1.NetworkSelectionElement
+	if shouldDeleteattachmentsAdded {
+		attachmentsToCancel = attachmentsToAdd
+	} else if addfailedIndex != -1 {
+		attachmentsToCancel = append(attachmentsToCancel, attachmentsToAdd[addfailedIndex])
```
[the remark this answers is not in the document]
Comment (maiqueb) [reply pkg/controller/pod.go:355]: this is a good point ... 

I agree with @LionelJouin; shouldn't you delete all the attachments you've just added ? i.e. setting the pod back to its original state ? 

otherwise, the pod's network-status and the pod's actual interfaces will not be consistent.

**Review by maiqueb — CHANGES_REQUESTED** [review]
Thank you for this PR. I agree we should keep the pod's interfaces consistent with the reported network-status at all times. Extra thanks for complying and adding the unit test @LionelJouin requested.

I'm requesting some changes to improve the overall code quality, and I also wonder if your approach (only deleting one interface) wouldn't break the pod interface / pod network status consistency.

**Review by maiqueb — COMMENTED** [review]
It looks good. 

@LionelJouin could you please review ? 
@oshoval could you help me out in this one ? 

I think this is close to a merge, thanks ! And sorry it took so long for me to review it.

File: pkg/controller/pod.go [hunk 12]
```diff
@@ -254,8 +259,13 @@ func (pnc *PodNetworksController) processNextWorkItem() bool {
 				PodSandboxID: podSandboxID,
 			})
 		if err != nil {
+			// The number of results will always less than len of attachmentsToAdd if err != nil.
+			attachmentsToRollback = attachmentsToAdd[:len(results)+1]
 			klog.Errorf("error adding attachments: %v", err)
 			return true
+		} else {
+			// If update pod network status successed we rollbak nothing after handleResult.
```
Comment (oshoval) [inline pkg/controller/pod.go:267]: nit: i think we can drop this comment
as it depends on `handleResult`
here we just set `attachmentsToRollback` to equal the whole `attachmentsToAdd` because
`handleDynamicInterfaceRequest` succeed
so the comment might be bit confusing and not required here imho

**Review by oshoval — COMMENTED** [review]
thanks nice
just a nit so far

**Review by maiqueb — APPROVED** [review]
Pending CI results, this looks good. 

I'll take a last quick review on Monday, then, assuming I don't see anything weird, I'll proceed with the merge.

Huge thanks for the contribution, and for your patience. I'm aware this took more than anticipated ...

**Comment by maiqueb** [comment]
I see your PR now fails the linter tests ... Sorry about that. 

Let me take a quick look; FWIW, I'm considering merging it and fixing it myself afterwards.

Really sorry this is taking so long.

**Review by maiqueb — APPROVED** [review]
Let's bring this in.

I'll fix the main branch on a follow up PR. 

Huge thanks.
