### PR TITLE
Fix e2e tests on crio providers

### LINKED ISSUE #140: [BUG] e2e tests failing on kubevirtci providers
**Describe the bug**
The e2e tests are deterministically failing on kubevirtci providers. This often happens on the tests request the pod interfaces to have a statically set MAC address.

The following error can be seen in the logs:
```
E0426 07:55:43.773202       1 pod.go:222] error adding attachments: failed to ADD delegate: unexpected CNI response status 400: '&{ContainerID:d700ae73b86d6ffd50053bcc961ae74a6b391cef93d94051902132801c00d5e5 Netns:/var/run/netns/b45beb46-6399-4480-8b0a-66acc5f8fc13 IfName:ens58 Args:K8S_POD_NAMESPACE=ns1;K8S_POD_NAME=tiny-winy-pod;K8S_POD_UID=5217fe2f-e1a8-4907-bd13-5198a70d3720 Path: StdinData:[123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 48 34 44 34 100 105 115 97 98 108 101 67 104 101 99 107 34 58 116 114 117 101 44 34 110 97 109 101 34 58 34 116 101 110 97 110 116 45 110 101 116 119 111 114 107 34 44 34 112 108 117 103 105 110 115 34 58 91 123 34 109 97 115 116 101 114 34 58 34 101 116 104 48 34 44 34 109 111 100 101 34 58 34 98 114 105 100 103 101 34 44 34 116 121 112 101 34 58 34 109 97 99 118 108 97 110 34 125 93 44 10 32 32 32 32 34 99 104 114 111 111 116 68 105 114 34 58 32 34 47 104 111 115 116 114 111 111 116 34 44 10 32 32 32 32 34 99 111 110 102 68 105 114 34 58 32 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 44 10 32 32 32 32 34 108 111 103 76 101 118 101 108 34 58 32 34 118 101 114 98 111 115 101 34 44 10 32 32 32 32 34 115 111 99 107 101 116 68 105 114 34 58 32 34 47 104 111 115 116 47 114 117 110 47 109 117 108 116 117 115 47 34 44 10 32 32 32 32 34 99 110 105 86 101 114 115 105 111 110 34 58 32 34 48 46 51 46 49 34 44 10 32 32 32 32 34 99 110 105 67 111 110 102 105 103 68 105 114 34 58 32 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 44 10 32 32 32 32 34 109 117 108 116 117 115 67 111 110 102 105 103 70 105 108 101 34 58 32 34 97 117 116 111 34 44 10 32 32 32 32 34 109 117 108 116 117 115 65 117 116 111 99 111 110 102 105 103 68 105 114 34 58 32 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 10 125 10]} {ContainerID:d700ae73b86d6ffd50053bcc961ae74a6b391cef93d94051902132801c00d5e5 Netns:/var/run/netns/b45beb46-6399-4480-8b0a-66acc5f8fc13 IfName:ens58 Args:K8S_POD_NAMESPACE=ns1;K8S_POD_NAME=tiny-winy-pod;K8S_POD_UID=5217fe2f-e1a8-4907-bd13-5198a70d3720 Path: StdinData:[123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 48 34 44 34 100 105 115 97 98 108 101 67 104 101 99 107 34 58 116 114 117 101 44 34 110 97 109 101 34 58 34 116 101 110 97 110 116 45 110 101 116 119 111 114 107 34 44 34 112 108 117 103 105 110 115 34 58 91 123 34 109 97 115 116 101 114 34 58 34 101 116 104 48 34 44 34 109 111 100 101 34 58 34 98 114 105 100 103 101 34 44 34 116 121 112 101 34 58 34 109 97 99 118 108 97 110 34 125 93 44 10 32 32 32 32 34 99 104 114 111 111 116 68 105 114 34 58 32 34 47 104 111 115 116 114 111 111 116 34 44 10 32 32 32 32 34 99 111 110 102 68 105 114 34 58 32 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 44 10 32 32 32 32 34 108 111 103 76 101 118 101 108 34 58 32 34 118 101 114 98 111 115 101 34 44 10 32 32 32 32 34 115 111 99 107 101 116 68 105 114 34 58 32 34 47 104 111 115 116 47 114 117 110 47 109 117 108 116 117 115 47 34 44 10 32 32 32 32 34 99 110 105 86 101 114 115 105 111 110 34 58 32 34 48 46 51 46 49 34 44 10 32 32 32 32 34 99 110 105 67 111 110 102 105 103 68 105 114 34 58 32 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 44 10 32 32 32 32 34 109 117 108 116 117 115 67 111 110 102 105 103 70 105 108 101 34 58 32 34 97 117 116 111 34 44 10 32 32 32 32 34 109 117 108 116 117 115 65 117 116 111 99 111 110 102 105 103 68 105 114 34 58 32 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 10 125 10]} ERRORED: error configuring pod [ns1/tiny-winy-pod] networking: plugin type="macvlan" failed (add): failed to set "ens58" UP: address already in use

```

**Expected behavior**
The tests should pass.

**To Reproduce**
1. deploy the [CNAO's](https://github.com/kubevirt/cluster-network-addons-operator/#deployment) project; execute the following command from the project's root:
```
make cluster-up && make cluster-operator-push && make cluster-operator-install
```
2. provision the [following CR](https://github.com/kubevirt/cluster-network-addons-operator/#configuration)
4. run the dynamic-networks-controller e2e tests: `make e2e/test`

**Environment**:
- multus-dynamic-networks-controller version: N/A
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- OS (e.g. from /etc/os-release): N/A
- Controller configuration (`criSocketPath` / `multusSocketPath`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
This PR addresses failing e2e tests on kubevirtci providers.

It increases the timeouts a little bit, but the most important thing it does is ensure all pods are gone between tests, since the error we were seeing was a statically defined mac address being already used (which means the previous pod using it, is not yet deleted).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #140

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

File: e2e/e2e_test.go [hunk 1]
```diff
@@ -61,6 +62,14 @@ var _ = Describe("Multus dynamic networks controller", func() {
 			})
 		}
 
+		listPodsOnNamespace := func() []corev1.Pod {
+			pods, err := clients.ListPods(namespace, appLabel(podName))
```
Comment (oshoval) [inline e2e/e2e_test.go:66]: error can be etcd timeout basically, in this case you need to rerun, 
returning nil may be too early

Comment (maiqueb) [reply e2e/e2e_test.go:66]: I'm thinking of actually making this less generic, and ask what I really want to know:
```golang
		isTestNamespaceEmpty := func() bool {
			pods, err := clients.ListPods(namespace, appLabel(podName))
			if err != nil {
				return false
			}
			return len(pods.Items) == 0
		}
```

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1531/pull-e2e-cnao-multus-dynamic-networks-functests/1653007152383528960

this one failed after 5 seconds (assuming it is not my PR caused it, i saw this error as well without my PR (unless i miss something)
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1530/pull-e2e-cnao-multus-dynamic-networks-functests-release-0.85/1648196353093799936

**Comment by oshoval** [comment]
Can we proceed with those changes please ?

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by oshoval** [comment]
can we bump it on CNAO please ?
there are flakes there that this hopefully fix

**Comment by maiqueb** [comment]
> can we bump it on CNAO please ? there are flakes there that this hopefully fix

Feel free to do so. 

I personally would prefer to use this as an excuse to handle https://github.com/kubevirt/cluster-network-addons-operator/issues/1548 .

**Comment by oshoval** [comment]
can you create a release ? 
I see it is "tagged" so a release is needed

Sorry but I don't have time to handle the mentioned issue atm

**Comment by maiqueb** [comment]
IMO, it makes no sense to force a release when there are no production code changes.

CNAO should / must be updated to allow users to point at which test version of a component they want to use. That's what the [issue I've linked](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pull/141#issuecomment-1550962750) requests.

**Comment by oshoval** [comment]
I don't have time to handle it atm, and this is the case for all the components.
We have changes, the test changes which present flakes,  I don't think we should enforce other changes atm.
Please take it from here, in any way you would like.
