### PR TITLE
controller: reject adding ifaces to host networked pods

### LINKED ISSUE #88: [BUG] ignore host networked pods
**Describe the bug**
We are handling updates to pods running on the host network. There is nothing we can do for host networked pods.

**Expected behavior**
Updates to host networked pods should be ignored and logged by the controller. 

**To Reproduce**
1. Provision a host networked pod
2. Attach a network interface to it

**Environment**:
- multus-dynamic-networks-controller version: N/A
- Kubernetes version (use `kubectl version`): N/A
- Network-attachment-definition: N/A
- OS (e.g. from /etc/os-release): N/A
- Controller configuration (`criSocketPath` / `multusSocketPath`): N/A
- Kernel (e.g. `uname -a`): N/A
- Others: N/A

**Additional info / context**
Add any other information / context about the problem here.

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
This PR rejects adding / removing interfaces to/from host networked pods.

The controller unit tests were refactored a bit - creating the k8s client and the dummy controller - in a `JustBeforeEach` block to allow each `When` / `Context` block to define the pod previously. This way, there is a lot less duplicated code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #88

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

File: pkg/controller/pod.go [hunk 1]
```diff
@@ -243,6 +243,14 @@ func (pnc *PodNetworksController) handlePodUpdate(oldObj interface{}, newObj int
 	oldPod := oldObj.(*corev1.Pod)
 	newPod := newObj.(*corev1.Pod)
 
+	if newPod.Spec.HostNetwork {
+		klog.Warningf(
+			"rejecting to add interfaces for host networked pod: %s",
+			annotations.NamespacedName(newPod.GetNamespace(), newPod.GetName()),
+		)
+		pnc.Eventf(newPod, corev1.EventTypeWarning, "InterfaceAddRejected", rejectInterfaceAddEventFormat(newPod))
```
Comment (maiqueb) [inline pkg/controller/pod.go:251]: I'm assuming we want to both throw an event an log ... Maybe that's too much.

Any thoughts @kmabda ?

Comment (kmabda) [reply pkg/controller/pod.go:251]: I think it's a good idea to throw an event here to give a feedback to the user

**Review by kmabda — APPROVED** [review]

File: pkg/controller/pod.go (hunk 1 above)
Comment (kmabda) [reply pkg/controller/pod.go:251]: One thing, since in https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller/pull/90/files#diff-449e8d1bd46b9c978e208dde912a1d7a76d17ce553067f8d0a67a27f17338d26R152 we need to filter out hostnetwork pods as well but we can't tel before hand if an interface got added by the user or not until we process the request we could move this logic from `handlePodUpdate` to `processNextWorkItem` function.

**Pro** same treatment logic would be in one place i.e. we have a consistency w.r.t. filtering out unwanted pods and how we log/throw out an event to the user in case an interface got added for these pods in one place
**Con** a little more overhead by adding an item to the workqueue than removing it for processing

If you go ahead with these changes I can rebase my pull request once this one get merged.
